# Generated by Django 6.1 on 2026-08-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applokesh', '0004_followers_rename_images_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='images',
        ),
    ]
