# Generated by Django 6.1 on 2026-08-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applokesh', '0005_rename_image_post_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='images',
            new_name='image',
        ),
    ]
