# Generated by Django 6.1 on 2026-08-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applokesh', '0006_rename_images_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='blank-profile.png', upload_to='profile_images'),
        ),
    ]
